//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLabor
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int LaborTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LaborType LaborType { get; set; }
    }
}
